#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emulator state=pseudo_tiled


#bspc config focused_border_color "#00aacc"
bspc config focused_border_color "#111111"
bspc config normal_border_color "#222222"
bspc config urgent_border_color "#ff0000"
bspc config focus_follows_pointer false
bspc config click_to_focus button1

bspc config bottom_padding 0 

#xset s 300
#xrdb ~/.Xdefaults
## GNOME PolicyKit and Keyring
eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &

## for authentication
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

/usr/lib/x86_64-linux-gnu/openbox-xdg-autostart &

## Set root window colour
#hsetroot -solid "#2E3436" &

(sleep 2s; nitrogen --restore) &

## Start the tint2 session (the default tint2 will run if no sessions have been set)
(sleep 2s; bl-tint2-session) &

(sleep 2s; bl-compositor --start) &

## Start the Conky session (the default conkyrc will run if no sessions have been set)
(sleep 2s; bl-conky-session --autostart) &

## Volume control for systray
(sleep 2; volti) &

## Volume keys daemon
xfce4-volumed &

## Start Clipboard manager
#(sleep 3; clipit) &

## Start Thunar Daemon, if set as bl-file-manager
if [ "$(readlink -f $(which bl-file-manager))" = "$(which thunar)" ]
then
    thunar --daemon &
fi

## Enable power management
xfce4-power-manager &

## Start the battery applet
(sleep 2; fdpowermon) &

## Start xscreensaver (light-locker now used by default, run via XDG autostart.)
#xscreensaver -no-splash &

## Detect and configure touchpad. See 'man synclient' for more info.
if egrep -iq 'touchpad' /proc/bus/input/devices; then
    synclient VertEdgeScroll=1 &
    synclient HorizEdgeScroll=1 &
    synclient TapButton1=1 &
fi

syndaemon -k -i 0.5 -d &

## Set keyboard settings - 250 ms delay and 25 cps (characters per second) repeat rate.
## Adjust the values according to your preferances.
xset r rate 250 25 &

## Turn on/off system beep
xset b off &

## bl-welcome - post-installation script, will not run in a live session and
## only runs once. Safe to remove.
(sleep 10; bl-welcome --firstrun) &

## bl-fortune - have the system come up with a little adage (not yet enabled)
#(sleep 120; bl-fortune) &

wmname "LG3D" &

# Huion tablet remapping
xinput set-button-map `xinput list --id-only "PenTablet  Pen Pen (0)"` 20 21 22
xinput set-button-map `xinput list --id-only "PenTablet  Pad"` 23 24 25 26 27 28 29 30 31 32 33 34

pulseaudio --start &
